name: test_app
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  dio: ^4.0.6
  # responsive
  flutter_screenutil: ^5.5.3+2
  # state management 
  flutter_bloc: ^8.1.1
  bloc:
  # Cache & Storage
  flutter_secure_storage: ^8.0.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  
  easy_localization: ^3.0.0
  flutter_svg: ^1.1.1
  flutter_dotenv: ^5.0.2
  connectivity_plus: ^3.0.2
  internet_connection_checker: ^1.0.0+1
  yandex_mapkit: ^3.2.0
  geolocator: ^9.0.2
  permission_handler: ^10.2.0
  lottie:
  # for route
  
  auto_route: ^7.8.3


  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.6
  auto_route_generator: ^7.3.1
  hive_generator: ^2.0.1


flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/languages/
    - assets/fonts/
    - assets/icons/
    - .env


  fonts:
    - family: Manrope
      fonts:
        - asset: assets/fonts/Manrope-Bold.ttf
        - asset: assets/fonts/Manrope-ExtraBold.ttf
        - asset: assets/fonts/Manrope-SemiBold.ttf
          weight: 500


